### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by zhangjinhuang** [GavinCT/AndroidMultiChannelBuildTool#11]
大神，原谅我这个菜鸟，readme并没有解决我的疑问，ChannelUtil这个工具类应该在PythonTool之前就执行了，顺序都不同，当再生成渠道名空文件时ChannelUtil就不会再执行了，这样的话岂不是获取不到生成的渠道名了，也就无法再设置渠道名了，难道这样理解不对么？

**Comment by GavinCT** [comment]
JavaUtil放在android工程里。 打出来的apk用PythonUtil加工下。 Util为啥在Tool之前执行？

**Comment by zhangjinhuang** [comment]
我是这样理解的：PythonUtil是在进行多渠道打包时使用的，此时整个android项目工程已经完成了，而JavaUtil在android工程里，所以Util在Tool之前就已经执行了...

**Comment by GavinCT** [comment]
python把apk加工，apk中的信息被修改。   apk运行，利用内置的JavaUtil去读取被修改后的信息。  Util为什么会执行？ apk是用户执行的啊  你只是改动了apk 内置了读取逻辑  运行期间才去读取。 怎么回事Util比Tool执行早呢？

**Comment by GavinCT** [comment]
apk含有JavaUtil对吧， 这个apk被PythonTool加工写入了市场信息。  然后你把apk提供给了用户。 用户使用带有市场信息的、含有JavaUtil的apk， 用户点击运行，Util去读取Python写入的版本信息，这样解释应该清晰了吧

**Comment by zhangjinhuang** [comment]
嗯，算是理解了，谢谢大神的耐心解答，那这样子的话，是不是就可以在配置文件中不使用友盟的 <meta-data android:value="${UMENG_CHANNEL_VALUE}" android:name="UMENG_CHANNEL"/>配置了，因为JavaUtil读取的是META-INF下的那个渠道名的空文件？

**Comment by GavinCT** [comment]
你用友盟统计的话看readme。 不用的话就不需要了
