### ISSUE TITLE
这种方式在Android7.0以上安装出现签名问题

### ISSUE THREAD

**Issue by Caij** [GavinCT/AndroidMultiChannelBuildTool#17]
Failed to install C:\Users\Ca1j\PycharmProjects\AndroidMultiChannelBuildTool\PythonTool\output_emore-v1.2\emore-v1.2-3gcn.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl49141474.tmp/base.apk: META-INF/CERT.SF indicates /data/app/vmdl49141474.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]

 Python版本是3.5

**Comment by GavinCT** [comment]
请关闭v2签名，目前这种方式不适合v2签名  
针对v2签名新的打包方式美团即将发布

**Comment by Caij** [comment]
恩 昨天已经找到了问题。  你是美团的吗？

**Comment by GavinCT** [comment]
是的  我在美团  
参与了针对v2签名的新打包方式开发，新打包方式大概会在一月中旬发布技术博客

**Comment by Caij** [comment]
感谢！  先暂时用v1的签名方式
