### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by GithubOfJay** [GavinCT/AndroidMultiChannelBuildTool#18]
没打渠道包的release包是正常的所有设备都能安装  运行脚本生成渠道包之后  渠道包在小米手机上是正常的系统是android6.0  但在google pixel系统是原生7.1.1会提示软件包已损坏。

**Comment by GithubOfJay** [comment]
找到原因了

**Comment by GavinCT** [comment]
推荐使用 https://github.com/Meituan-Dianping/walle
