### ISSUE TITLE
安卓7.0

### ISSUE THREAD

**Issue by GithubOfJay** [GavinCT/AndroidMultiChannelBuildTool#19]
刚才以为是设置原因但这样设置了之后 在原生的7.1.1的pixel上还是会提示软件包已损坏啊。
 android {
    //...
    signingConfigs {
      release {
        v2SigningEnabled false 
      }
    }
  }

**Comment by GavinCT** [comment]
是否使用了什么加固？

**Comment by GithubOfJay** [comment]
没用第三方的加固软件但是不知道是不是因为混淆等下 写个简单的demo测试下

**Comment by GithubOfJay** [comment]
测试完毕 新建的demo还是会失败。
