### ISSUE TITLE
成功打包后, 使用反编译发现 AndroidManifest渠道还是没有变

### ISSUE THREAD

**Issue by chasel** [GavinCT/AndroidMultiChannelBuildTool#2]
你好, 我使用你的脚本在 OS X 下运行成功生成了多个渠道包, 然后我把生成的 APK包反编译后, 发现渠道号还是没有变化.
```xml
 <meta-data
            android:name="UMENG_CHANNEL"
            android:value="${umeng_channel}" />
```
是不是因为这个名字的关系.

**Comment by GavinCT** [comment]
博客里有说明，这种打包方式不是写入清单文件的

**Comment by chasel** [comment]
那我集成的友盟能识别到渠道吗?

**Comment by GavinCT** [comment]
![image](https://cloud.githubusercontent.com/assets/4016698/6140807/f7f1a844-b1d7-11e4-8efe-eb20bc3fb755.png)
答疑里面都写了啊

**Comment by GavinCT** [comment]
哪里是apk重新命名啊 想知道原理看博客。 想直接用起来就先把readme看完

**Comment by chasel** [comment]
哦, sorry, 我其实看到了, 但是我没有理解, 建议你可以写的更清楚些, 谢谢!
