### ISSUE TITLE
打包后的apk不能安装

### ISSUE THREAD

**Issue by XiaoYueBanZi** [GavinCT/AndroidMultiChannelBuildTool#20]
使用脚本打包后 在华为和vivo 小米 部分机型出现不能安装的情况 多出现在7.0系统 小米5.0也出现过 华为上会说没有证书

**Comment by GavinCT** [comment]
![image](https://cloud.githubusercontent.com/assets/4016698/24848953/ef48ef12-1dfb-11e7-9438-2d2d46010a7a.png)
