### ISSUE TITLE
渠道包不能安装-安装包未包含任何证书

### ISSUE THREAD

**Issue by guoGavin** [GavinCT/AndroidMultiChannelBuildTool#21]
v2签名方式已经关闭了
signingConfigs {
        release {
            ....
            v2SigningEnabled false
        }
    }
compileSdkVersion 25
buildToolsVersion '25.0.2'
minSdkVersion 17
targetSdkVersion 25
gradle:
com.android.tools.build:gradle:2.2.3

ps:我在你的脚本基础上稍微修改了一下，多写了一个空文件，一个是umeng的，一个是自己的业务逻辑的，但是我觉得应该不会有什么影响。

所以，有什么建议？

**Comment by GavinCT** [comment]
先确认下不适用此工具时 打出的包是否能正常安装吧

**Comment by guoGavin** [comment]
恩，这个是肯定尝试过的，不适用之前确认可用。难道是和我写入了两个空文件有关？

**Comment by GavinCT** [comment]
可以尝试下 如果直接用这个工具是否可以。  这样就知道到底是哪里代码有问题

从理论看，两个空文件是是可以的

**Comment by guoGavin** [comment]
恩，我这边尝试一下，暂时忙不开，晚点有结果了和你更新

**Comment by guoGavin** [comment]
我这边尝试了，你的py脚本没有进行任何更改，还是相同的结果
![sm8 o6 j vtglk egn cak](https://cloud.githubusercontent.com/assets/5715824/25123353/a587e558-245a-11e7-87c9-ba81da93e06c.png)

**Comment by guoGavin** [comment]
我的python信息：
![0_s 5 hx90zat _ 0xcnuln](https://cloud.githubusercontent.com/assets/5715824/25123601/869c3d14-245b-11e7-962e-af1f73ae39cb.png)

**Comment by guoGavin** [comment]
我这边用apksigner试了一下：
![1l 1 prchpk ag370cmzy](https://cloud.githubusercontent.com/assets/5715824/25126021/5ca1f60e-2463-11e7-831a-80cf84ca5cae.png)

**Comment by GavinCT** [comment]
想用v2 的话 去https://github.com/Meituan-Dianping/walle

**Comment by guoGavin** [comment]
我不想用v2，所以，前面我说的，我配置了v2SigningEnabled false，但是现在看起来貌似是这个没有生效？我只是在application的plugin添加了这句，其他的library的plugin并没有添加关闭v2的配置，这有关系吗？

**Comment by guoGavin** [comment]
而且，你看我导报的时候，提示的是我的配置生效了，或者你知道怎么查询导出包的签名版本
![Uploading LZT88)A1B@5]~JMS}_[E2BE.png…]()

**Comment by guoGavin** [comment]
我这边查了一下，的确是原始包，也使用了v2的签名，真是不知道为什么没有生效，估计我解决这个问题就可以
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Number of signers: 1

**Comment by guoGavin** [comment]
可以问一下，你使用的as和gradle版本吗？

**Comment by GavinCT** [comment]
我们使用的是walle 你那边是不是又什么别的插件影响了最终配置。

**Comment by guoGavin** [comment]
使用gradlew build --stacktrace 不经过as不会出现这种情况，原因暂时未明。
