### ISSUE TITLE
看到一篇文章说不建议使用空文件, 可能存在bug, 你看下呢

### ISSUE THREAD

**Issue by yyjdelete** [GavinCT/AndroidMultiChannelBuildTool#4]
http://www.jianshu.com/p/c21334dc14ef  

另外如果我打算改成往固定的xx_channel文件里面写入渠道名称,  是用writestr么

**Comment by GavinCT** [comment]
我联系作者确定下   改下python，往里面写点就行了

**Comment by GavinCT** [comment]
我在简书下评论一直没有回复。暂时不确定这个bug。 美团和为知笔记在使用过程中一直表现正常，应该暂时不用担心这个问题。
