### ISSUE TITLE
性能损耗

### ISSUE THREAD

**Issue by halzhang** [GavinCT/AndroidMultiChannelBuildTool#6]
我自己也实现过。
在META-INF下放一个空文件是不用重新签名，但是读取渠道的信息的时候实际上是一个解压+遍历文件的过程。apk 的体积一旦变大，这个过程耗时还是比较长的。对于用户来说体验很差。

虽然加快了多渠道打包，但是伤了用户。不知道你有没有什么解决方案？

**Comment by GavinCT** [comment]
每个版本有sp中的缓存，只是第一次较为耗时，但影响不大吧 可以看我的java实现。  总体感觉问题不大
