### ISSUE TITLE
渠道名称获取问题

### ISSUE THREAD

**Issue by asker517** [GavinCT/AndroidMultiChannelBuildTool#9]
感谢作者提供这个非常棒的工具。用起来也非常棒。 但是我觉得这里有个小小的问题，就是``ChannelUtil``里面保存渠道名到sp文件这里，假如我安装了小米渠道包，然后运行程序，这时候保存的xiaomi ；但是我又从360下载了一个相同的apk，覆盖安装，这时候进程序，去取channel名称的时候，先会从sharepreference里面获取，因为覆盖安装sp文件不会被清除，所以这时候获取到的仍然是前一次的channel名称(xiaomi)，我大概测试了一下是存在这个小问题的。:D

**Comment by GavinCT** [comment]
是存在这个问题，因为跟版本相关联 除非覆盖安装的是不同版本（versioncode不同）
这里算是个取舍吧，因为从zip里面去读取信息也是耗时的，每次这么去找没有太大必要，而且渠道只是简单做个统计，没必要太精确吧。
当然如果更希望精确的话，也可以存在一个变量里，每次程序重新启动需要的时候都去取一下，之后运行期间都从变量里拿，这样可能更符合你的用途。
